# Generated by Django 3.1.7 on 2021-04-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postcomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='commenter',
        ),
    ]
